
-   id: saxon-xsl-compile
    name: saxon-xsl-compile
    description: ''
    entry: saxon-xsl-compile
    language: node
    'types': [xsl]
    args: []
    require_serial: false
    minimum_pre_commit_version: '0'